### ISSUE TITLE
Bakım

### ISSUE THREAD

**Issue by 3alkan** [erenerisken/robotdegilim.xyz#2]
Hocam selam,
yeni dönem yaklaşıyor veriler hala güncellenmedi. Devralan birisi yoksa site bakımına yardımcı olmak isterim.

**Comment by alpaylan** [comment]
Selamlar,

Aynen devralan kimse olmadı şu ana kadar. İsterseniz kendi fork'unuzda güncellemeyi yapın, sonrasında main'e birleştirelim, sizi de maintainer olarak ekleyelim.

**Comment by 3alkan** [comment]
Hocam,
vaktiniz varsa bir ufak görüşme yapsak. Projenin genel yapısını aktarsanız. Problemler neler, nelerin değiştirilmesi gerekiyor gibi şeyleri anlatsanız güzel olur.

**Comment by alpaylan** [comment]
Tabii hocam. Çarşamba ya da Cuma TSİ 18.00 sonrasında müsaitliğiniz var mıdır?

**Comment by 3alkan** [comment]
Çarşamba 18.00 den sonra okey hocam.
iletişim maili: 3alkan@gmail.com
