### ISSUE TITLE
Haftalık program kayma sorunu

### ISSUE THREAD

**Issue by 3alkan** [erenerisken/robotdegilim.xyz#6]
![image](https://github.com/user-attachments/assets/d67fae7e-4a24-47c7-a52e-ea8e591cd776)
![Ekran görüntüsü 2024-09-20 215840](https://github.com/user-attachments/assets/2907428b-6fea-4c73-8a70-cb37f5f07fb0)
haftalık programda koyu yere tıklıyorum ama üste ekliyor ve derslerde biraz kaymış

**Comment by alpaylan** [comment]
There is even a funnier bug. You can add multiple `Full` signs but they're actually idempotent, deleting one deletes all of them. @erenerisken you wanna fix it or should I?

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/19af95a8-dddd-45fc-ae91-7623ffa3085a">

**Comment by erenerisken** [comment]
İlk bug'ı reproduce edemedim, tam olarak hangi senaryoda oluşuyor bu kayma?

<img width="1920" alt="Screenshot 2024-09-24 at 16 57 05" src="https://github.com/user-attachments/assets/11a46ec6-c8cb-4ddf-8bda-c92af1b151ce">

**Comment by 3alkan** [comment]
weekly programda kursların boyutu ve konumu belli ki bir şeye bağlı olarak değişiyor, muhtemel screen size gibi, buna bağlı olarak da farklı cihazlarda kayma oluşuyor.

**Comment by 3alkan** [comment]
https://drive.google.com/file/d/18IRaUaWAW7xImSKkx8g5nvXRs5vqWywr/view?usp=sharing

Weekly program automaticall grow up.
is it okay, or is it unexpected behavior?

**Comment by erenerisken** [comment]
Yes it is a result of the mitigation we implemented today against overflowing course names

**Comment by erenerisken** [comment]
First bug reported in this issue should be resolved after that mitigation.

**Comment by erenerisken** [comment]
Can you confirm @3alkan ?

**Comment by 3alkan** [comment]
yes it is solved.
